python -W ignore src/nih/multi_eval_nih.py --image_save_dir /data/mariammaa/nih_multi_label/perturbed_nih_topk/ --results_dir /data/mariammaa/nih_multi_label/nih_results_topk_integratedgrad/ --evaluate_subset --sal_method integrated_gradients --net_basename full_cluster2-0_1_2_3_4_5_6_7_8_9_10_11_12_13-resnext-lr:0.01-wd:0.0_spring-cloud-30 --tasks 0_1_2_3_4_5_6_7_8_9_10_11_12_13
python -W ignore src/nih/multi_eval_nih.py --image_save_dir /data/mariammaa/nih_multi_label/perturbed_nih_topk/ --results_dir /data/mariammaa/nih_multi_label/nih_results_topk_integratedgrad/ --evaluate_subset --sal_method integrated_gradients --net_basename full_cluster2-14-resnext-lr:0.01-wd:0.0_deep-darkness-34 --tasks 14

python -W ignore src/nih/multi_eval_nih.py --image_save_dir /data/mariammaa/nih_multi_label/perturbed_nih_topk/ --results_dir /data/mariammaa/nih_multi_label/nih_results_topk_integratedgrad/ --evaluate_subset --sal_method integrated_gradients --net_basename full_cluster3-0_1_2_3_6_8_9-resnext-lr:0.01-wd:0.0_whole-sea-31 --tasks 0_1_2_3_6_8_9
python -W ignore src/nih/multi_eval_nih.py --image_save_dir /data/mariammaa/nih_multi_label/perturbed_nih_topk/ --results_dir /data/mariammaa/nih_multi_label/nih_results_topk_integratedgrad/ --evaluate_subset --sal_method integrated_gradients --net_basename full_cluster3-4_5_7_10_11_12_13-resnext-lr:0.01-wd:0.0_cerulean-dew-33 --tasks 4_5_7_10_11_12_13

python -W ignore src/nih/multi_eval_nih.py --image_save_dir /data/mariammaa/nih_multi_label/perturbed_nih_topk/ --results_dir /data/mariammaa/nih_multi_label/nih_results_topk_integratedgrad/ --evaluate_subset --sal_method integrated_gradients --net_basename full_cluster4-0_2_3_8-resnext-lr:0.01-wd:0.0_cool-aardvark-35 --tasks 0_2_3_8
python -W ignore src/nih/multi_eval_nih.py --image_save_dir /data/mariammaa/nih_multi_label/perturbed_nih_topk/ --results_dir /data/mariammaa/nih_multi_label/nih_results_topk_integratedgrad/ --evaluate_subset --sal_method integrated_gradients --net_basename full_cluster4-1_6_7_9_10_11_13-resnext-lr:0.01-wd:0.0_curious-galaxy-36 --tasks 1_6_7_9_10_11_13
python -W ignore src/nih/multi_eval_nih.py --image_save_dir /data/mariammaa/nih_multi_label/perturbed_nih_topk/ --results_dir /data/mariammaa/nih_multi_label/nih_results_topk_integratedgrad/ --evaluate_subset --sal_method integrated_gradients --net_basename full_cluster4-4_5_12-resnext-lr:0.01-wd:0.0_swept-jazz-37 --tasks 4_5_12
