# python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-0_12_16_22_30_38resnext-lr:0.01-wd:0.0_usual-glitter-7 --tasks 0_12_16_22_30_38 --sal_method saliency_map --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_saliencymap/
# python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-10_13_14_15_23resnext-lr:0.01-wd:0.0_clean-morning-37 --tasks 10_13_14_15_23 --sal_method saliency_map --evaluate_subset --results_dir   /data/mariammaa/celeba/results_manipulate_saliencymap/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-4_17_28resnext-lr:0.01-wd:0.0_lilac-dream-30 --tasks 4_17_28 --sal_method saliency_map --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_saliencymap/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-5_33_35resnext-lr:0.01-wd:0.0_jolly-dew-31 --tasks 5_33_35 --sal_method saliency_map --evaluate_subset --results_dir  /data/mariammaa/celeba/results_manipulate_saliencymap/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-9_11_26_32resnext-lr:0.01-wd:0.0_rosy-star-35 --tasks 9_11_26_32 --sal_method saliency_map --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_saliencymap/

python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-0_12_16_22_30_38resnext-lr:0.01-wd:0.0_usual-glitter-7 --tasks 0_12_16_22_30_38 --sal_method integrated_gradients --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_integratedgrad
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-10_13_14_15_23resnext-lr:0.01-wd:0.0_clean-morning-37 --tasks 10_13_14_15_23 --sal_method integrated_gradients --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_integratedgrad
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-4_17_28resnext-lr:0.01-wd:0.0_lilac-dream-30 --tasks 4_17_28 --sal_method integrated_gradients --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_integratedgrad
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-5_33_35resnext-lr:0.01-wd:0.0_jolly-dew-31 --tasks 5_33_35 --sal_method integrated_gradients --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_integratedgrad
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-9_11_26_32resnext-lr:0.01-wd:0.0_rosy-star-35 --tasks 9_11_26_32 --sal_method integrated_gradients --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_integratedgrad

python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-0_12_16_22_30_38resnext-lr:0.01-wd:0.0_usual-glitter-7 --tasks 0_12_16_22_30_38 --sal_method gradcam --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_gradcam/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-10_13_14_15_23resnext-lr:0.01-wd:0.0_clean-morning-37 --tasks 10_13_14_15_23 --sal_method gradcam --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_gradcam/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-4_17_28resnext-lr:0.01-wd:0.0_lilac-dream-30 --tasks 4_17_28 --sal_method gradcam --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_gradcam/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-5_33_35resnext-lr:0.01-wd:0.0_jolly-dew-31 --tasks 5_33_35 --sal_method gradcam --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_gradcam/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-9_11_26_32resnext-lr:0.01-wd:0.0_rosy-star-35 --tasks 9_11_26_32 --sal_method gradcam --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_gradcam/

python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-0_12_16_22_30_38resnext-lr:0.01-wd:0.0_usual-glitter-7 --tasks 0_12_16_22_30_38 --sal_method input_x_gradient --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_inputxgradient/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-10_13_14_15_23resnext-lr:0.01-wd:0.0_clean-morning-37 --tasks 10_13_14_15_23 --sal_method input_x_gradient --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_inputxgradient/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-4_17_28resnext-lr:0.01-wd:0.0_lilac-dream-30 --tasks 4_17_28 --sal_method input_x_gradient --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_inputxgradient/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-5_33_35resnext-lr:0.01-wd:0.0_jolly-dew-31 --tasks 5_33_35 --sal_method input_x_gradient --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_inputxgradient/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-9_11_26_32resnext-lr:0.01-wd:0.0_rosy-star-35 --tasks 9_11_26_32 --sal_method input_x_gradient --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_inputxgradient/

python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-0_12_16_22_30_38resnext-lr:0.01-wd:0.0_usual-glitter-7 --tasks 0_12_16_22_30_38 --sal_method guidedBackprop --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_guidedbackprop/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-10_13_14_15_23resnext-lr:0.01-wd:0.0_clean-morning-37 --tasks 10_13_14_15_23 --sal_method guidedBackprop --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_guidedbackprop/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-4_17_28resnext-lr:0.01-wd:0.0_lilac-dream-30 --tasks 4_17_28 --sal_method guidedBackprop --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_guidedbackprop/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-5_33_35resnext-lr:0.01-wd:0.0_jolly-dew-31 --tasks 5_33_35 --sal_method guidedBackprop --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_guidedbackprop/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-9_11_26_32resnext-lr:0.01-wd:0.0_rosy-star-35 --tasks 9_11_26_32 --sal_method guidedBackprop --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_guidedbackprop/

python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-0_12_16_22_30_38resnext-lr:0.01-wd:0.0_usual-glitter-7 --tasks 0_12_16_22_30_38 --sal_method guided_gradcam --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_guidedgradcam/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-10_13_14_15_23resnext-lr:0.01-wd:0.0_clean-morning-37 --tasks 10_13_14_15_23 --sal_method guided_gradcam --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_guidedgradcam/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-4_17_28resnext-lr:0.01-wd:0.0_lilac-dream-30 --tasks 4_17_28 --sal_method guided_gradcam --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_guidedgradcam/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-5_33_35resnext-lr:0.01-wd:0.0_jolly-dew-31 --tasks 5_33_35 --sal_method guided_gradcam --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_guidedgradcam/
python -W ignore src/celeba/multi_eval_celeba.py --net_basename _manipulate_cluster8-9_11_26_32resnext-lr:0.01-wd:0.0_rosy-star-35 --tasks 9_11_26_32 --sal_method guided_gradcam --evaluate_subset --results_dir /data/mariammaa/celeba/results_manipulate_guidedgradcam/
